apiVersion: v1
kind: Service
metadata: 
  name: my-clusterip-service
  namespace: django-todo-app
spec:
  selector:
    app: django-todo-app
  clusterIP: 10.101.39.5 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
